# Vocabulary.create(category:"fruit" ,name: "banana",image_url:"https://images.pexels.com/photos/1166648/pexels-photo-1166648.jpeg" )
# Vocabulary.create(category:"fruit" ,name:"blackberry" ,image_url: "https://images.pexels.com/photos/87736/pexels-photo-87736.jpeg")
# Vocabulary.create(category:"fruit" ,name: "blood orange",image_url:"https://images.pexels.com/photos/943632/pexels-photo-943632.jpeg" )
# Vocabulary.create(category:"fruit" ,name: "blueberry",image_url: "https://images.pexels.com/photos/131054/pexels-photo-131054.jpeg")
# Vocabulary.create(category:"fruit" ,name: "cantaloupe",image_url: "https://images.pexels.com/photos/1622421/pexels-photo-1622421.jpeg")
# Vocabulary.create(category:"fruit" ,name: "cherry",image_url:"https://images.pexels.com/photos/109274/pexels-photo-109274.jpeg" )
# Vocabulary.create(category:"fruit" ,name:"clementine" ,image_url: "https://images.pexels.com/photos/327098/pexels-photo-327098.jpeg")
# Vocabulary.create(category:"fruit" ,name:"coconut" ,image_url: "https://images.pexels.com/photos/221074/pexels-photo-221074.jpeg")
# Vocabulary.create(category:"fruit" ,name:"cranberry" ,image_url: "https://images.pexels.com/photos/306800/pexels-photo-306800.jpeg")
# Vocabulary.create(category:"fruit" ,name: "orange",image_url: "https://images.pexels.com/photos/1293120/pexels-photo-1293120.jpeg")
# Vocabulary.create(category:"fruit" ,name: "pear",image_url: "https://images.pexels.com/photos/568471/pexels-photo-568471.jpeg")
# Vocabulary.create(category:"fruit" ,name: "pineapple",image_url:"https://images.pexels.com/photos/1161547/pexels-photo-1161547.jpeg" )
# Vocabulary.create(category:"fruit" ,name: "grapes",image_url: "https://images.pexels.com/photos/708777/pexels-photo-708777.jpeg")
# Vocabulary.create(category:"fruit" ,name: "grapefruit",image_url:"https://images.pexels.com/photos/209549/pexels-photo-209549.jpeg" )
# Vocabulary.create(category:"fruit" ,name: "kiwi",image_url: "https://images.pexels.com/photos/51312/kiwi-fruit-vitamins-healthy-eating-51312.jpeg")
# Vocabulary.create(category:"fruit" ,name: "mango",image_url: "https://images.pexels.com/photos/918643/pexels-photo-918643.jpeg")

#
# Vocabulary.create(category: "vegetable", name:"mushroom" ,image_url: "https://images.pexels.com/photos/40566/fly-agaric-mushroom-nature-red-40566.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "vegetable", name:"asparagus" ,image_url:"https://images.pexels.com/photos/351679/pexels-photo-351679.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "vegetable", name:"beet" ,image_url:"https://images.pexels.com/photos/1229357/pexels-photo-1229357.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "vegetable", name:"broccoli" ,image_url:"https://images.pexels.com/photos/1359326/pexels-photo-1359326.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "vegetable", name:"cabbage" ,image_url: "https://images.pexels.com/photos/968254/pexels-photo-968254.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "vegetable", name:"carrot" ,image_url: "https://images.pexels.com/photos/37641/carrots-basket-vegetables-market-37641.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "vegetable", name:"cauliflower" ,image_url: "https://images.pexels.com/photos/461245/pexels-photo-461245.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "vegetable", name:"celery" ,image_url: "https://images.pexels.com/photos/34494/soup-greens-celery-vegetables-food.jpg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "vegetable", name:"green bean" ,image_url:"https://images.pexels.com/photos/1680585/pexels-photo-1680585.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "vegetable", name:"fennel" ,image_url:"https://images.pexels.com/photos/159471/fennel-vegetables-fennel-bulb-food-159471.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "vegetable", name:"corn" ,image_url:"https://images.pexels.com/photos/547263/pexels-photo-547263.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "vegetable", name:"cucumber" ,image_url: "https://images.pexels.com/photos/37528/cucumber-salad-food-healthy-37528.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "vegetable", name:"eggplant" ,image_url:"https://images.pexels.com/photos/321551/pexels-photo-321551.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "vegetable", name:"garlic" ,image_url:"https://images.pexels.com/photos/928251/pexels-photo-928251.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "vegetable", name:"ginger" ,image_url:"https://images.pexels.com/photos/161556/ginger-plant-asia-rhizome-161556.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "vegetable", name:"bell pepper" ,image_url:"https://images.pexels.com/photos/128536/pexels-photo-128536.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "vegetable", name:"jalapeno" ,image_url: "https://images.pexels.com/photos/1472866/pexels-photo-1472866.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "vegetable", name:"kale" ,image_url: "https://images.pexels.com/photos/51372/kale-vegetables-brassica-oleracea-var-sabellica-l-51372.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "vegetable", name:"zucchini" ,image_url:"https://images.pexels.com/photos/128420/pexels-photo-128420.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "vegetable", name:"onion" ,image_url:"https://images.pexels.com/photos/1446269/pexels-photo-1446269.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "vegetable", name:"potato" ,image_url: "https://images.pexels.com/photos/144248/potatoes-vegetables-erdfrucht-bio-144248.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "vegetable", name:"radish" ,image_url:"https://images.pexels.com/photos/244393/pexels-photo-244393.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "vegetable", name:"squash" ,image_url:"https://images.pexels.com/photos/53458/butternut-squash-fresh-vegetable-soup-vegetable-53458.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "vegetable", name:"tomato" ,image_url: "https://images.pexels.com/photos/5617/red-tomato-vegetable.jpg?auto=compress&cs=tinysrgb&h=650&w=940")


# Vocabulary.create(category: "clothes", name:"ball gown" ,image_url: "https://images.pexels.com/photos/265705/pexels-photo-265705.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "clothes", name: "belt",image_url:"https://images.pexels.com/photos/83403/pexels-photo-83403.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "clothes", name:"slippers" ,image_url: "https://images.pexels.com/photos/1444417/pexels-photo-1444417.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "clothes", name: "boots",image_url:"https://images.pexels.com/photos/266840/pexels-photo-266840.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "clothes", name: "bow tie",image_url:"https://images.pexels.com/photos/161030/groom-wedding-marry-marriage-161030.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "clothes", name: "sneakers",image_url: "https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "clothes", name: "cufflinks",image_url:"https://images.pexels.com/photos/1327446/pexels-photo-1327446.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "clothes", name: "dress",image_url:"https://images.pexels.com/photos/985635/pexels-photo-985635.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "clothes", name: "gloves",image_url:"https://images.pexels.com/photos/63448/pexels-photo-63448.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "clothes", name:"hat" ,image_url: "https://images.pexels.com/photos/8333/fashion-hat-straw-hat.jpg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "clothes", name: "hoody",image_url:"https://images.pexels.com/photos/1183266/pexels-photo-1183266.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "clothes", name: "jeans",image_url: "https://images.pexels.com/photos/52518/jeans-pants-blue-shop-52518.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "clothes", name: "raincoat",image_url: "https://images.pexels.com/photos/1686861/pexels-photo-1686861.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "clothes", name: "scarf",image_url:"https://images.pexels.com/photos/1436134/pexels-photo-1436134.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "clothes", name: "high heel shoes",image_url: "https://images.pexels.com/photos/336372/pexels-photo-336372.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "clothes", name: "skirt",image_url:"https://images.pexels.com/photos/601316/pexels-photo-601316.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "clothes", name: "socks",image_url: "https://images.pexels.com/photos/251454/pexels-photo-251454.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
#
# Vocabulary.create(category: "animal", name: "rabbit",image_url:"https://images.pexels.com/photos/372166/pexels-photo-372166.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "animal", name:"parakeet" ,image_url:"https://images.pexels.com/photos/51161/parakeet-yellow-parakeet-green-parakeet-bird-51161.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "animal", name: "baboon",image_url:"https://images.pexels.com/photos/38280/monkey-mandril-africa-baboon-38280.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "animal", name:"peacock" ,image_url: "https://images.pexels.com/photos/45911/peacock-plumage-bird-peafowl-45911.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "animal", name: "bear",image_url:"https://images.pexels.com/photos/158109/kodiak-brown-bear-adult-portrait-wildlife-158109.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "animal", name: "parrot",image_url: "https://images.pexels.com/photos/40984/animal-ara-macao-beak-bird-40984.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "animal", name: "bison",image_url: "https://images.pexels.com/photos/46188/bison-buffalo-american-animal-46188.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "animal", name: "raccoon",image_url: "https://images.pexels.com/photos/54602/raccoon-bear-zoo-saeugentier-54602.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "animal", name: "bull",image_url:"https://images.pexels.com/photos/16009/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "animal", name: "camel",image_url: "https://images.pexels.com/photos/839265/pexels-photo-839265.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "animal", name:"cat" ,image_url: "https://images.pexels.com/photos/104827/cat-pet-animal-domestic-104827.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "animal", name:"cheetah" ,image_url:"https://images.pexels.com/photos/162313/cheetah-sitting-big-cat-feline-162313.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "animal", name: "cougar",image_url:"https://images.pexels.com/photos/53001/cougar-mountain-lion-puma-concolor-big-cat-53001.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "animal", name: "cow",image_url: "https://images.pexels.com/photos/422218/pexels-photo-422218.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "animal", name:"crocodile" ,image_url:"https://images.pexels.com/photos/60644/nile-crocodile-crocodylus-niloticus-zoo-60644.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "animal", name:"deer" ,image_url: "https://images.pexels.com/photos/34231/antler-antler-carrier-fallow-deer-hirsch.jpg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "animal", name: "dog",image_url:"https://images.pexels.com/photos/8700/wall-animal-dog-pet.jpg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "animal", name:"donkey" ,image_url:"https://images.pexels.com/photos/598751/pexels-photo-598751.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "animal", name:"giraffe" ,image_url:"https://images.pexels.com/photos/1619507/pexels-photo-1619507.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "animal", name:"gorilla" ,image_url:"https://images.pexels.com/photos/913652/pexels-photo-913652.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "animal", name:"hippopotamus" ,image_url:"https://images.pexels.com/photos/667201/pexels-photo-667201.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "animal", name: "horse",image_url: "https://images.pexels.com/photos/45164/mare-animal-nature-ride-45164.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "animal", name:"goat" ,image_url: "https://images.pexels.com/photos/86594/goat-animal-horns-black-and-white-86594.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "animal", name: "lamb",image_url: "https://images.pexels.com/photos/891607/pexels-photo-891607.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "animal", name:"lion" ,image_url: "https://images.pexels.com/photos/247502/pexels-photo-247502.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "animal", name:"zebra" ,image_url:"https://images.pexels.com/photos/750539/pexels-photo-750539.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )



# Vocabulary.create(category: "body",name:"hand",image_url:"https://images.pexels.com/photos/255527/pexels-photo-255527.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "body",name:"foot",image_url:"https://images.pexels.com/photos/1204473/pexels-photo-1204473.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "body",name:"arm",image_url:"https://images.pexels.com/photos/1257770/pexels-photo-1257770.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "body",name:"finger",image_url:"https://images.pexels.com/photos/652355/pexels-photo-652355.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "body",name:"nail",image_url: "https://images.pexels.com/photos/939835/pexels-photo-939835.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "body",name:"toe",image_url: "https://images.pexels.com/photos/266011/pexels-photo-266011.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "body",name:"bones",image_url: "https://images.pexels.com/photos/1528375/pexels-photo-1528375.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "body",name:"head",image_url: "https://images.pexels.com/photos/137595/pexels-photo-137595.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "body",name:"neck",image_url:"https://images.pexels.com/photos/531057/pexels-photo-531057.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "body",name:"nose",image_url:"https://images.pexels.com/photos/792994/pexels-photo-792994.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "body",name:"teeth",image_url: "https://images.pexels.com/photos/925301/pexels-photo-925301.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "body",name:"eyes",image_url:"https://images.pexels.com/photos/206388/pexels-photo-206388.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "random",name:"toothbrush",image_url:"https://images.pexels.com/photos/298611/pexels-photo-298611.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "random",name:"car",image_url:"https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "random",name:"bus",image_url: "https://images.pexels.com/photos/1178448/pexels-photo-1178448.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "random",name:"airplane",image_url:"https://images.pexels.com/photos/46148/aircraft-jet-landing-cloud-46148.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "random",name:"mountain",image_url: "https://images.pexels.com/photos/417173/pexels-photo-417173.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "random",name:"sky",image_url:  "https://images.pexels.com/photos/912110/pexels-photo-912110.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "random",name:"house",image_url:"https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "random",name:"phone",image_url: "https://images.pexels.com/photos/33999/pexels-photo.jpg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "random",name:"chalk",image_url: "https://images.pexels.com/photos/226588/pexels-photo-226588.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "random",name:"playground",image_url:"https://images.pexels.com/photos/133458/pexels-photo-133458.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "random",name:"bicycle",image_url: "https://images.pexels.com/photos/276517/pexels-photo-276517.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "random",name:"water",image_url: "https://images.pexels.com/photos/40784/drops-of-water-water-nature-liquid-40784.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "random",name:"computer",image_url: "https://images.pexels.com/photos/238118/pexels-photo-238118.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "random",name:"building",image_url: "https://images.pexels.com/photos/273209/pexels-photo-273209.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
#
# Vocabulary.create(category: "number",name: "one",image_url:"https://images.pexels.com/photos/1061142/pexels-photo-1061142.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "number",name: "two", image_url:"https://images.pexels.com/photos/1061141/pexels-photo-1061141.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "number",name: "three", image_url: "https://images.pexels.com/photos/1061140/pexels-photo-1061140.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "number",name: "four", image_url: "https://images.pexels.com/photos/1061139/pexels-photo-1061139.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "number",name: "five", image_url: "https://images.pexels.com/photos/1061138/pexels-photo-1061138.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "number",name: "six", image_url: "https://images.pexels.com/photos/1061137/pexels-photo-1061137.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "number",name: "seven", image_url: "https://images.pexels.com/photos/1061136/pexels-photo-1061136.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "number",name: "eight", image_url:"https://images.pexels.com/photos/1061135/pexels-photo-1061135.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category: "number",name: "nine", image_url: "https://images.pexels.com/photos/1061134/pexels-photo-1061134.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "number",name: "ten", image_url:"https://images.pexels.com/photos/1339845/pexels-photo-1339845.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "number",name: "eleven", image_url: "https://images.pexels.com/photos/1655998/pexels-photo-1655998.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "number",name: "twenty four", image_url:"https://images.pexels.com/photos/13893/people-training-muscles-gym-13893.jpg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "number",name: "one hundred", image_url: "https://images.pexels.com/photos/52541/dollar-bill-100-euro-money-banknote-52541.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "number",name: "zero", image_url:"https://images.pexels.com/photos/1447235/pexels-photo-1447235.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "number",name: "one hundred twenty three", image_url: "https://images.pexels.com/photos/1314536/pexels-photo-1314536.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category: "number",name: "one thousand", image_url: "https://images.pexels.com/photos/164638/pexels-photo-164638.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# 
#
# Vocabulary.create(category:"fruit" ,name: "banana",image_url: "https://images.pexels.com/photos/1166648/pexels-photo-1166648.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category:"fruit" ,name:"blackberry" ,image_url:"https://images.pexels.com/photos/257834/pexels-photo-257834.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category:"fruit" ,name:"apple" ,image_url: "https://images.pexels.com/photos/39803/pexels-photo-39803.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category:"fruit" ,name: "blood orange",image_url:"https://images.pexels.com/photos/943632/pexels-photo-943632.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category:"fruit" ,name: "blueberry",image_url:"https://images.pexels.com/photos/131054/pexels-photo-131054.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category:"fruit" ,name: "cantaloupe",image_url: "https://images.pexels.com/photos/1622421/pexels-photo-1622421.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category:"fruit" ,name: "cherry",image_url:"https://images.pexels.com/photos/109274/pexels-photo-109274.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category:"fruit" ,name:"clementine" ,image_url:"https://images.pexels.com/photos/327098/pexels-photo-327098.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category:"fruit" ,name:"coconut" ,image_url: "https://images.pexels.com/photos/221074/pexels-photo-221074.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category:"fruit" ,name:"cranberry" ,image_url:"https://images.pexels.com/photos/139917/pexels-photo-139917.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category:"fruit" ,name: "orange",image_url: "https://images.pexels.com/photos/42059/citrus-diet-food-fresh-42059.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category:"fruit" ,name: "pear",image_url:"https://images.pexels.com/photos/568471/pexels-photo-568471.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category:"fruit" ,name: "pineapple",image_url:"https://images.pexels.com/photos/139259/pexels-photo-139259.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category:"fruit" ,name: "grapes",image_url:"https://images.pexels.com/photos/708777/pexels-photo-708777.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category:"fruit" ,name: "grapefruit",image_url: "https://images.pexels.com/photos/1435734/pexels-photo-1435734.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
# Vocabulary.create(category:"fruit" ,name: "kiwi",image_url:"https://images.pexels.com/photos/51312/kiwi-fruit-vitamins-healthy-eating-51312.jpeg?auto=compress&cs=tinysrgb&h=650&w=940" )
# Vocabulary.create(category:"fruit" ,name: "mango",image_url: "https://images.pexels.com/photos/39303/mango-tropical-fruit-juicy-sweet-39303.jpeg?auto=compress&cs=tinysrgb&h=650&w=940")
